version: '3.8'

services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - '2222:22'
    volumes:
      - './Gitlab_Data/configs:/etc/gitlab'
      - './Gitlab_Data/data:/var/opt/gitlab'
      - './Gitlab_Data/logs:/var/log/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #external_url "http://10.10.10.2"
        gitlab_rails['initial_root_password'] = "your_root_password"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_encoding'] = "unicode"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "123"
        gitlab_rails['db_host'] = "postgres"
        gitlab_rails['db_port'] = 5432
        #                 nginx                #
        #nginx['enable'] = false
        #gitlab_rails['gitlab_https'] = true
        #gitlab_rails['gitlab_port'] = 443
        #gitlab_rails['gitlab_host'] = '127.0.0.1'
        #                 redis                #
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
    networks:
      - git-net
    deploy:
      replicas: 1
      resources:
        limits:
          memory: "10GB"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: gitlabhq_production
    volumes:
      - ./postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
    networks:
      - git-net


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
    networks:
      - git-net
    depends_on:
      - gitlab

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PORT=6379
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - git-net

networks:
  git-net:
    driver: overlay
